### ISSUE TITLE
Segurança de segredos

### ISSUE THREAD

**Issue by rafaelcanovas** [gabriel-guelfi/acmevita#1]
Boa tarde Gabriel, tudo bem?

Existe uma certa preocupação em misturar valores de configuração com código, ainda mais quando estamos falando de segredos, senhas, chaves secretas. 

> A litmus test for whether an app has all config correctly factored out of the code is whether the codebase could be made open source at any moment, without compromising any credentials.

https://12factor.net/config

Como você resolveria esse problema, considerando que este código seria implantado em diversos ambientes ou máquinas virtuais?

https://github.com/gabriel-guelfi/acmevita/blob/9eab272a1ea4e3b55c4f8b4adb0b2492bbb84808/config.json#L1-L9

**Comment by gabriel-guelfi** [comment]
Olá, bom dia, Rafael! Tudo bem, sim e contigo?

Entendi. Bem, eu usei exatamente o quê eles sugerem no próprio link do 12-factor que você compartilhou: variáveis de ambiente.

Para isso eu segui os seguintes passos:

1. Removi o arquivo *config.json* e a rotina de leitura deste arquivo em *main.py*:
https://github.com/gabriel-guelfi/acmevita/blob/7391f9e20724fab346c772dbc7240077e93171f7/main.py#L1-L16
2. Alterei a classe *Dbconfig* para importar os valores das variáveis de ambiente:
https://github.com/gabriel-guelfi/acmevita/blob/7391f9e20724fab346c772dbc7240077e93171f7/core/dbconfig.py#L1-L22

**Comment by rafaelcanovas** [comment]
Perfeito Gabriel,

Obrigado!
