### ISSUE TITLE
Escolhas técnicas

### ISSUE THREAD

**Issue by rafaelcanovas** [gabriel-guelfi/acmevita#2]
Boa tarde Gabriel, tudo bem?

Queria entender algumas escolhas técnicas feitas nesse trecho.

https://github.com/gabriel-guelfi/acmevita/blob/9eab272a1ea4e3b55c4f8b4adb0b2492bbb84808/application/routes.py#L14-L17

1. Por que realizar o import no escopo da função?
2. Por que criar uma variável temporária `service` para receber a classe `DepartmentService`?

Obrigado!

**Comment by gabriel-guelfi** [comment]
Bom dia, Rafael! Tudo certo?

Vamos lá:

1. Realizei o import dentro das funções para que o sistema importe apenas os recursos necessários para aquele ciclo de request/response que está acessando a rota. Se tem uma solução melhor pra isso, poderia me mostrar, por gentileza?

2. Pelo hábito que peguei de outras linguagens, de salvar a instância de uma classe em uma variável para poder manipulá-la, mas aqui neste contexto, realmente não faz nenhum sentido. Alterei e ficou desta forma:
https://github.com/gabriel-guelfi/acmevita/blob/7391f9e20724fab346c772dbc7240077e93171f7/application/routes.py#L5-L15

**Comment by rafaelcanovas** [comment]
Perfeito Gabriel,

Obrigado!
