### ISSUE TITLE
Camada de serviço

### ISSUE THREAD

**Issue by rafaelcanovas** [gabriel-guelfi/acmevita#3]
Fala Gabriel, tudo beleza?

Na aplicação da AcmeVita isso não é exatamente um problema. No entanto a medida que uma API vai crescendo a complexidade da chamada "camada de serviço" aumenta, e normalmente temos que separar ela em camadas mais especializadas. Considerando que no código abaixo temos 3 responsabilidades:

- Deserialização (banco de dados para aplicação)
- Regras de negócio (lógica especifica da operação)
- Serialização (aplicação para resposta da API)

Como você reescreveria esse código pensando em responsabilidades mais bem definidas?

https://github.com/gabriel-guelfi/acmevita/blob/9eab272a1ea4e3b55c4f8b4adb0b2492bbb84808/application/services/departmentservice.py#L17-L26

**Comment by gabriel-guelfi** [comment]
Bom dia, Rafael!

Transferi a deserialização(DB -> app) para o model:
https://github.com/gabriel-guelfi/acmevita/blob/7391f9e20724fab346c772dbc7240077e93171f7/application/models.py#L3-L11

Mantive o loop de processamento dos dados no *Service*:
https://github.com/gabriel-guelfi/acmevita/blob/7391f9e20724fab346c772dbc7240077e93171f7/application/services/departmentservice.py#L7-L21

E a serialização(app -> API response) já estava no arquivo de rota (*routes.py*):
https://github.com/gabriel-guelfi/acmevita/blob/7391f9e20724fab346c772dbc7240077e93171f7/application/routes.py#L15

**Comment by rafaelcanovas** [comment]
Perfeito Gabriel,

Obrigado!
